fix service to work with DTO instead of Entity
AndriiMovhan/Shop pull request #1
Opened 2022-01-29 23:09 UTC by AndriiMovhan

fix service to work with DTO instead of Entity

2022-01-29 23:43 UTC, financeasist requested changes

2022-01-29 23:43 UTC, financeasist commented on pom.xml
> +            <artifactId>hibernate-core</artifactId>
why do we need this?

2022-01-29 23:43 UTC, financeasist commented on src/main/java/com/example/shop/service/GoodServiceImpl.java
> +    public GoodDto update(GoodDto id) {
please add `@Transactional` to all methods that modifies an entity and `@Transactional(readOnly = true)`  to all find methods

2022-01-29 23:43 UTC, financeasist commented on src/main/java/com/example/shop/service/GoodServiceImpl.java
> +    public GoodDto update(GoodDto id) {
`update(GoodDto id)`  ?? is it really valid name here?

2022-02-10 22:42 UTC, AndriiMovhan commented on pom.xml
> +            <artifactId>hibernate-core</artifactId>
I fix this

2022-02-13 00:01 UTC, AndriiMovhan commented on src/main/java/com/example/shop/service/GoodServiceImpl.java
> +    public GoodDto update(GoodDto id) {
I add this

2022-02-13 00:01 UTC, AndriiMovhan commented on src/main/java/com/example/shop/service/GoodServiceImpl.java
> +    public GoodDto update(GoodDto id) {
I fix this

2022-02-13 16:37 UTC, AndriiMovhan commented on src/main/java/com/example/shop/service/GoodServiceImpl.java
> +    public GoodDto update(GoodDto id) {
I fix this

2022-02-20 21:36 UTC, merged